const _ = require('lodash');
const { BSON } = require('bson');

/**
 * Common response processing function
 * @param {*} data - Response data
 * @param {Response} response - Response object
 * @param {Function} resolve - Promise resolve function
 * @param {Function} reject - Promise reject function
 * @param {Function} [successMapper] - Function to customize success response
 * @param {Function} [errorMapper] - Function to customize error response
 */
const processResponse = (data, response, resolve, reject, successMapper = null, errorMapper = null) => {
  if (response.ok === true) {
    if (successMapper) {
      try {
        const result = successMapper(data, response);
        resolve(result);
      } catch (error) {
        reject({ error, response });
      }
    } else {
      // Detect gating basic response structure: check if it's { type, name, data } format
      // Response generated by gating middleware: { type: 'response', name: 'ok', code: 200, data: {...} }
      const target = data || {};
      if (_.has(target, 'type') && _.has(target, 'name') && _.has(target, 'data')) {
        resolve({ data: target.data, response, success: target });
      } else {
        // General JSON response: return original data as is
        resolve({ data, response });
      }
    }
  } else {
    if (errorMapper) {
      try {
        const result = errorMapper(data, response);
        reject(result);
      } catch (error) {
        reject({ error, response });
      }
    } else {
      reject({ error: data, response });
    }
  }
};

/**
 * Function to handle JSON response
 * @param {Object} params - { response, resolve, reject, successMapper?, errorMapper? }
 */
const handleJson = ({ response, resolve, reject, successMapper = null, errorMapper = null }) => {
  response.json().then((jsn) => {
    processResponse(jsn, response, resolve, reject, successMapper, errorMapper);
  }).catch((error) => {
    reject({ error, response });
  });
};

/**
 * Function to handle BSON response
 * @param {Object} params - { response, resolve, reject, successMapper?, errorMapper? }
 */
const handleBson = ({ response, resolve, reject, successMapper = null, errorMapper = null }) => {
  response.arrayBuffer().then((buffer) => {
    const data = BSON.deserialize(new Uint8Array(buffer));
    processResponse(data, response, resolve, reject, successMapper, errorMapper);
  }).catch((error) => {
    reject({ error, response });
  });
};

/**
 * Universal HTTP client function
 * Automatically handles JSON or BSON responses based on Content-Type
 * @param {string|Request} url - Request URL or Request object
 * @param {Object} [options] - Options object
 * @param {Function} [options.successMapper] - Function to customize success response
 * @param {Function} [options.errorMapper] - Function to customize error response
 * @param {Object} [options.fetchOptions] - Additional options to pass to fetch function
 * @returns {Promise} - { data, response, success? } or { error, response }
 */
const dataFetch = (url, options = {}) => {
  const { successMapper = null, errorMapper = null, ...fetchOptions } = options;

  return new Promise((resolve, reject) => {
    fetch(url, fetchOptions)
      .then((response) => {
        const contentType = (
          (typeof response.headers?.get === 'function' ? response.headers.get('content-type') : null) ||
          _.get(response, 'headers.map.content-type') ||
          _.get(response, 'headers.map.Content-Type') ||
          ''
        ).toLowerCase();
        if (contentType.includes('json')) {
          handleJson({ response, resolve, reject, successMapper, errorMapper });
        } else if (contentType.includes('bson')) {
          handleBson({ response, resolve, reject, successMapper, errorMapper });
        } else {
          if (response.ok === true) {
            resolve({ data: {}, response });
          } else {
            reject({
              error: {
                status: response.status,
                statusText: response.statusText,
                url: response.url,
                contentType: contentType
              },
              response
            });
          }
        }
      })
      .catch((error) => {
        reject({ error });
      });
  });
};

module.exports = {
  dataFetch,
  handleJson,
  handleBson
};
